CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId integer REFERENCES projects(id)
);

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES('Make a web app', 1, 'Using JavaScript', '2019-05-12');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES('Make an app', 1, 'Using Dart', '2019-05-13');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES('Make a desktop app', 1, 'Using C++', '2019-05-14');

--Insert for the task table
INSERT INTO tasks(name, done, projectId)
    VALUES('Download vuejs', false ,1);

INSERT INTO tasks(name, done, projectId)
    VALUES('Create UI Web', false ,1);

INSERT INTO tasks(name, done, projectId)
    VALUES('Download Flutter', false ,2);

INSERT INTO tasks(name, done, projectId)
    VALUES('Design UI', false ,2);